# Generated by Django 5.1 on 2024-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_date", models.DateField()),
                ("code", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("release_date", "code")},
            },
        ),
    ]
